# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - end_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - spin_main_joint
      - shoulder_main_joint
      - elbow_main_joint
      - wrist_main_joint
      - forearm_main_joint
      - wrist_arm_joint
    action_ns: follow_joint_trajectory
    default: true
  end_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
    action_ns: follow_joint_trajectory
    default: true