# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    end_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - spin_main_joint
      - shoulder_main_joint
      - elbow_main_joint
      - wrist_main_joint
      - forearm_main_joint
      - wrist_arm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
end_controller:
  ros__parameters:
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position